### ISSUE TITLE
The build step mentions the file is compiled but output folder contains nothing

### ISSUE THREAD

**Issue by randomguyingithub** [nukdokplex/autohotkey-build#3]
The *releases* folder has one ahk file that the *build* step tries to compile from and output to testfolder.
The log shows the file successfully compiled, but when you check with *ls* there is nothing inside the testfolder:

yml file: https://github.com/randomguyingithub/arensalogxclaimer/blob/fe1215ea483248e3cbdf079c1e2f4a75e69477cd/.github/workflows/buildtest1.yml

log: https://github.com/randomguyingithub/arensalogxclaimer/actions/runs/5520628914/jobs/10067523705

**Comment by nukdokplex** [comment]
I've noticed that you use v0.1, try latest v1

**Comment by randomguyingithub** [comment]
It is user error, switching the AHK version fixes it since my script was in v2, sorry for bothering you
